import { useNavigate } from "react-router-dom";
import "./About.css";

const About = () => {
    const navigate = useNavigate();

    return (
        <div className="about-container">
            {/* Rank Models Section */}
            <div className="TextElement">
                <h2>🔹 Rank models for job description</h2>
                <p>You can rank these models based on cosine similarity between job descriptions and summaries generated by them.</p>
                <button className="about-btn about-btn-rank" onClick={() => navigate("/Rank")}>Rank Models</button>
            </div>

            {/* Section Heading */}
            <h1>About Summarization Methods</h1>

            {/* BART & BERT Container */}
            <div className="flex-container">
                {/* BART Card */}
                <div className="summarization-box">
                    <h2>🔹 BART Abstractive Summarization</h2>
                    <p>BART is a deep learning model designed for **abstractive summarization**. It generates human-like summaries by rephrasing and compressing content.</p>
                    <button className="about-btn about-btn-bart" onClick={() => navigate("/bart")}>BART Summarization</button>
                </div>

                {/* BERT Card */}
                <div className="summarization-box">
                    <h2>🔹 BERT Extractive Summarization</h2>
                    <p>BERT selects **important sentences** rather than generating new ones. It is ideal for factual summarization, preserving the original wording while reducing content length.</p>
                    <button className="about-btn about-btn-bert" onClick={() => navigate("/bert")}>BERT Summarization</button>
                </div>
            </div>
        </div>
    );
};

export default About;
